"""add_resource_details_column_to_conversation_table

Revision ID: 082939899ed2
Revises: a2347f3390b4
Create Date: 2025-09-23 12:49:40.903721

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "082939899ed2"
down_revision: Union[str, None] = "a2347f3390b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations", sa.Column("resource_details", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations", "resource_details")
    # ### end Alembic commands ###
